-- DO $$ BEGIN
--  CREATE TYPE "data_resource_providers" AS ENUM('postgres');
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  CREATE TYPE "flow_types" AS ENUM('route', 'workflow', 'component');
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  CREATE TYPE "primitive_types" AS ENUM('iterator', 'conditional-branch', 'function', 'workflow', 'route');
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "tasks" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"job_id" varchar(32) NOT NULL,
-- 	"position" integer NOT NULL,
-- 	"name" varchar(256),
-- 	"state" varchar(10) NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"scheduled_at" timestamp,
-- 	"started_at" timestamp,
-- 	"completed_at" timestamp,
-- 	"failed_at" timestamp,
-- 	"cmd" text[],
-- 	"entrypoint" text[],
-- 	"run_script" text,
-- 	"image" varchar(256),
-- 	"registry" jsonb,
-- 	"env" jsonb,
-- 	"files_" jsonb,
-- 	"queue" varchar(256),
-- 	"error_" text,
-- 	"pre_tasks" jsonb,
-- 	"post_tasks" jsonb,
-- 	"mounts" jsonb,
-- 	"node_id" varchar(32),
-- 	"retry" jsonb,
-- 	"limits" jsonb,
-- 	"timeout" varchar(8),
-- 	"result" text,
-- 	"var" varchar(64),
-- 	"parallel" jsonb,
-- 	"parent_id" varchar(32),
-- 	"each_" jsonb,
-- 	"description" text,
-- 	"subjob" jsonb,
-- 	"networks" text[],
-- 	"gpus" text,
-- 	"if_" text,
-- 	"tags" text[]
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "tasks_log_parts" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"number_" integer NOT NULL,
-- 	"task_id" varchar(32) NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"contents" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "waitlist" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"email" text NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL,
-- 	CONSTRAINT "waitlist_email_unique" UNIQUE("email")
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "user" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"name" text,
-- 	"email" text NOT NULL,
-- 	"emailVerified" timestamp,
-- 	"image" text
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "session" (
-- 	"sessionToken" text PRIMARY KEY NOT NULL,
-- 	"userId" text NOT NULL,
-- 	"expires" timestamp NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "workspaces" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"name" text NOT NULL,
-- 	"description" text,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "data_resources" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"name" text NOT NULL,
-- 	"description" text,
-- 	"provider" "data_resource_providers" NOT NULL,
-- 	"metadata" jsonb NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL,
-- 	"workspace_id" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "primitives" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"name" text NOT NULL,
-- 	"description" text,
-- 	"type" "primitive_types" NOT NULL,
-- 	"position_x" integer DEFAULT 0 NOT NULL,
-- 	"position_y" integer DEFAULT 0 NOT NULL,
-- 	"metadata" jsonb NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL,
-- 	"flow_id" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "edges" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"source" text NOT NULL,
-- 	"target" text NOT NULL,
-- 	"flow_id" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "flows" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"name" text NOT NULL,
-- 	"description" text,
-- 	"type" "flow_types" NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL,
-- 	"workspace_id" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "nodes" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"name" varchar(64) NOT NULL,
-- 	"queue" varchar(64) NOT NULL,
-- 	"started_at" timestamp NOT NULL,
-- 	"last_heartbeat_at" timestamp NOT NULL,
-- 	"cpu_percent" double precision NOT NULL,
-- 	"status" varchar(10) NOT NULL,
-- 	"hostname" varchar(128) NOT NULL,
-- 	"task_count" integer NOT NULL,
-- 	"version_" varchar(32) NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "jobs" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"name" varchar(256),
-- 	"state" varchar(10) NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"started_at" timestamp,
-- 	"completed_at" timestamp,
-- 	"failed_at" timestamp,
-- 	"tasks" jsonb NOT NULL,
-- 	"position" integer NOT NULL,
-- 	"inputs" jsonb NOT NULL,
-- 	"context" jsonb NOT NULL,
-- 	"description" text,
-- 	"parent_id" varchar(32),
-- 	"task_count" integer NOT NULL,
-- 	"output_" text,
-- 	"result" text,
-- 	"error_" text,
-- 	"defaults" jsonb,
-- 	"webhooks" jsonb,
-- 	"ts" "tsvector" NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "verificationToken" (
-- 	"identifier" text NOT NULL,
-- 	"token" text NOT NULL,
-- 	"expires" timestamp NOT NULL,
-- 	CONSTRAINT "verificationToken_identifier_token_pk" PRIMARY KEY("identifier","token")
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "account" (
-- 	"userId" text NOT NULL,
-- 	"type" text NOT NULL,
-- 	"provider" text NOT NULL,
-- 	"providerAccountId" text NOT NULL,
-- 	"refresh_token" text,
-- 	"access_token" text,
-- 	"expires_at" integer,
-- 	"token_type" text,
-- 	"scope" text,
-- 	"id_token" text,
-- 	"session_state" text,
-- 	CONSTRAINT "account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
-- );
-- --> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_state" ON "tasks" ("state");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_job_id" ON "tasks" ("job_id");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_log_parts_task_id" ON "tasks_log_parts" ("task_id");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_log_parts_created_at" ON "tasks_log_parts" ("created_at");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_nodes_heartbeat" ON "nodes" ("last_heartbeat_at");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_jobs_state" ON "jobs" ("state");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "jobs_ts_idx" ON "jobs" ("ts");--> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "tasks" ADD CONSTRAINT "tasks_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON DELETE no action ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "tasks_log_parts" ADD CONSTRAINT "tasks_log_parts_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE no action ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "session" ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "data_resources" ADD CONSTRAINT "data_resources_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "primitives" ADD CONSTRAINT "primitives_flow_id_flows_id_fk" FOREIGN KEY ("flow_id") REFERENCES "public"."flows"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "edges" ADD CONSTRAINT "edges_source_primitives_id_fk" FOREIGN KEY ("source") REFERENCES "public"."primitives"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "edges" ADD CONSTRAINT "edges_target_primitives_id_fk" FOREIGN KEY ("target") REFERENCES "public"."primitives"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "edges" ADD CONSTRAINT "edges_flow_id_flows_id_fk" FOREIGN KEY ("flow_id") REFERENCES "public"."flows"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "flows" ADD CONSTRAINT "flows_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
