-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations

-- CREATE TABLE IF NOT EXISTS "nodes" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"name" varchar(64) NOT NULL,
-- 	"queue" varchar(64) NOT NULL,
-- 	"started_at" timestamp NOT NULL,
-- 	"last_heartbeat_at" timestamp NOT NULL,
-- 	"cpu_percent" double precision NOT NULL,
-- 	"status" varchar(10) NOT NULL,
-- 	"hostname" varchar(128) NOT NULL,
-- 	"task_count" integer NOT NULL,
-- 	"version_" varchar(32) NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "jobs" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"name" varchar(256),
-- 	"state" varchar(10) NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"started_at" timestamp,
-- 	"completed_at" timestamp,
-- 	"failed_at" timestamp,
-- 	"tasks" jsonb NOT NULL,
-- 	"position" integer NOT NULL,
-- 	"inputs" jsonb NOT NULL,
-- 	"context" jsonb NOT NULL,
-- 	"description" text,
-- 	"parent_id" varchar(32),
-- 	"task_count" integer NOT NULL,
-- 	"output_" text,
-- 	"result" text,
-- 	"error_" text,
-- 	"defaults" jsonb,
-- 	"webhooks" jsonb,
-- 	"ts" "tsvector" NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "tasks" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"job_id" varchar(32) NOT NULL,
-- 	"position" integer NOT NULL,
-- 	"name" varchar(256),
-- 	"state" varchar(10) NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"scheduled_at" timestamp,
-- 	"started_at" timestamp,
-- 	"completed_at" timestamp,
-- 	"failed_at" timestamp,
-- 	"cmd" text[],
-- 	"entrypoint" text[],
-- 	"run_script" text,
-- 	"image" varchar(256),
-- 	"registry" jsonb,
-- 	"env" jsonb,
-- 	"files_" jsonb,
-- 	"queue" varchar(256),
-- 	"error_" text,
-- 	"pre_tasks" jsonb,
-- 	"post_tasks" jsonb,
-- 	"mounts" jsonb,
-- 	"node_id" varchar(32),
-- 	"retry" jsonb,
-- 	"limits" jsonb,
-- 	"timeout" varchar(8),
-- 	"result" text,
-- 	"var" varchar(64),
-- 	"parallel" jsonb,
-- 	"parent_id" varchar(32),
-- 	"each_" jsonb,
-- 	"description" text,
-- 	"subjob" jsonb,
-- 	"networks" text[],
-- 	"gpus" text,
-- 	"if_" text,
-- 	"tags" text[]
-- );
-- --> statement-breakpoint
-- CREATE TABLE IF NOT EXISTS "tasks_log_parts" (
-- 	"id" varchar(32) PRIMARY KEY NOT NULL,
-- 	"number_" integer NOT NULL,
-- 	"task_id" varchar(32) NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"contents" text NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_nodes_heartbeat" ON "nodes" ("last_heartbeat_at");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_jobs_state" ON "jobs" ("state");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "jobs_ts_idx" ON "jobs" ("ts");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_state" ON "tasks" ("state");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_job_id" ON "tasks" ("job_id");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_log_parts_task_id" ON "tasks_log_parts" ("task_id");--> statement-breakpoint
-- CREATE INDEX IF NOT EXISTS "idx_tasks_log_parts_created_at" ON "tasks_log_parts" ("created_at");--> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "tasks" ADD CONSTRAINT "tasks_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON DELETE no action ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
-- --> statement-breakpoint
-- DO $$ BEGIN
--  ALTER TABLE "tasks_log_parts" ADD CONSTRAINT "tasks_log_parts_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE no action ON UPDATE no action;
-- EXCEPTION
--  WHEN duplicate_object THEN null;
-- END $$;
