import { z } from "zod";

export const taskTypeSchema = z.enum(["database", "endpoint", "page"]);

export const taskSchema = z.object({
  id: z.string().describe("Unique task identifier (autogenerated)"),
  name: z.string().describe("Human readable task name"),
  type: taskTypeSchema.describe("High-level component type"),
  description: z.string().describe("What exactly needs to be built"),
  dependencies: z
    .array(z.string())
    .default([])
    .describe("Task IDs that must complete first"),
  acceptanceCriteria: z
    .array(z.string())
    .describe("Specific, testable requirements for completion"),
});

export const planSchema = z.object({
  description: z.string().describe("What this plan accomplishes"),
  tasks: z.array(taskSchema).describe("High-level architectural tasks"),
});
